import { db, type Exercise, type Settings } from "./db";

const EXERCISES: Exercise[] = [
  // Chest
  {
    id: "bench-press",
    name: "Barbell Bench Press",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "barbell",
    category: "compound",
    substituteIds: ["db-bench", "machine-chest-press"],
  },
  {
    id: "db-bench",
    name: "Dumbbell Bench Press",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "shoulders"],
    equipment: "dumbbell",
    category: "compound",
    substituteIds: ["bench-press"],
  },
  {
    id: "incline-db-press",
    name: "Incline Dumbbell Press",
    muscleGroup: "chest",
    secondaryMuscles: ["shoulders"],
    equipment: "dumbbell",
    category: "compound",
  },
  {
    id: "machine-chest-press",
    name: "Machine Chest Press",
    muscleGroup: "chest",
    equipment: "machine",
    category: "compound",
    substituteIds: ["bench-press"],
  },
  {
    id: "pushup",
    name: "Push-up",
    muscleGroup: "chest",
    secondaryMuscles: ["triceps", "core"],
    equipment: "bodyweight",
    category: "compound",
  },
  {
    id: "cable-fly",
    name: "Cable Fly",
    muscleGroup: "chest",
    equipment: "cable",
    category: "isolation",
  },
  // Back
  {
    id: "pullup",
    name: "Pull-up",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "pullup-bar",
    category: "compound",
  },
  {
    id: "chinup",
    name: "Chin-up",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "pullup-bar",
    category: "compound",
  },
  {
    id: "barbell-row",
    name: "Barbell Row",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "barbell",
    category: "compound",
  },
  {
    id: "db-row",
    name: "Dumbbell Row",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "dumbbell",
    category: "compound",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    muscleGroup: "back",
    secondaryMuscles: ["biceps"],
    equipment: "cable",
    category: "compound",
  },
  {
    id: "deadlift",
    name: "Deadlift",
    muscleGroup: "back",
    secondaryMuscles: ["hamstrings", "glutes"],
    equipment: "barbell",
    category: "compound",
  },
  // Shoulders
  {
    id: "ohp",
    name: "Overhead Press",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "barbell",
    category: "compound",
  },
  {
    id: "db-shoulder-press",
    name: "Dumbbell Shoulder Press",
    muscleGroup: "shoulders",
    secondaryMuscles: ["triceps"],
    equipment: "dumbbell",
    category: "compound",
  },
  {
    id: "lateral-raise",
    name: "Lateral Raise",
    muscleGroup: "shoulders",
    equipment: "dumbbell",
    category: "isolation",
  },
  {
    id: "face-pull",
    name: "Face Pull",
    muscleGroup: "shoulders",
    secondaryMuscles: ["back"],
    equipment: "cable",
    category: "isolation",
  },
  // Arms
  {
    id: "barbell-curl",
    name: "Barbell Curl",
    muscleGroup: "biceps",
    equipment: "barbell",
    category: "isolation",
  },
  {
    id: "db-curl",
    name: "Dumbbell Curl",
    muscleGroup: "biceps",
    equipment: "dumbbell",
    category: "isolation",
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    muscleGroup: "biceps",
    secondaryMuscles: ["forearms"],
    equipment: "dumbbell",
    category: "isolation",
  },
  {
    id: "tricep-pushdown",
    name: "Tricep Pushdown",
    muscleGroup: "triceps",
    equipment: "cable",
    category: "isolation",
  },
  {
    id: "skullcrusher",
    name: "Skullcrusher",
    muscleGroup: "triceps",
    equipment: "barbell",
    category: "isolation",
  },
  {
    id: "dip",
    name: "Dip",
    muscleGroup: "triceps",
    secondaryMuscles: ["chest"],
    equipment: "bodyweight",
    category: "compound",
  },
  // Legs
  {
    id: "squat",
    name: "Back Squat",
    muscleGroup: "quads",
    secondaryMuscles: ["glutes", "hamstrings"],
    equipment: "barbell",
    category: "compound",
  },
  {
    id: "front-squat",
    name: "Front Squat",
    muscleGroup: "quads",
    secondaryMuscles: ["core"],
    equipment: "barbell",
    category: "compound",
  },
  {
    id: "leg-press",
    name: "Leg Press",
    muscleGroup: "quads",
    secondaryMuscles: ["glutes"],
    equipment: "machine",
    category: "compound",
  },
  {
    id: "rdl",
    name: "Romanian Deadlift",
    muscleGroup: "hamstrings",
    secondaryMuscles: ["glutes"],
    equipment: "barbell",
    category: "compound",
  },
  {
    id: "leg-curl",
    name: "Leg Curl",
    muscleGroup: "hamstrings",
    equipment: "machine",
    category: "isolation",
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    muscleGroup: "quads",
    equipment: "machine",
    category: "isolation",
  },
  {
    id: "hip-thrust",
    name: "Hip Thrust",
    muscleGroup: "glutes",
    secondaryMuscles: ["hamstrings"],
    equipment: "barbell",
    category: "compound",
  },
  {
    id: "bulgarian-split-squat",
    name: "Bulgarian Split Squat",
    muscleGroup: "quads",
    secondaryMuscles: ["glutes"],
    equipment: "dumbbell",
    category: "compound",
  },
  {
    id: "calf-raise",
    name: "Calf Raise",
    muscleGroup: "calves",
    equipment: "machine",
    category: "isolation",
  },
  // Core
  {
    id: "plank",
    name: "Plank",
    muscleGroup: "core",
    equipment: "bodyweight",
    category: "isolation",
  },
  {
    id: "hanging-leg-raise",
    name: "Hanging Leg Raise",
    muscleGroup: "core",
    equipment: "pullup-bar",
    category: "isolation",
  },
  {
    id: "ab-wheel",
    name: "Ab Wheel",
    muscleGroup: "core",
    equipment: "other",
    category: "isolation",
  },
];

export async function seedDatabase() {
  const count = await db.exercises.count();
  if (count === 0) {
    await db.exercises.bulkAdd(EXERCISES);
  }
  const s = await db.settings.get("app");
  if (!s) {
    const defaults: Settings = {
      id: "app",
      unit: "kg",
      theme: "dark",
      language: "en",
      defaultRest: 120,
      notificationsEnabled: false,
      availableEquipment: [
        "barbell",
        "dumbbell",
        "bench",
        "pullup-bar",
        "machine",
        "cable",
        "bodyweight",
        "band",
      ],
      weeklyGoal: 4,
      createdAt: Date.now(),
      userName: "",
    };
    await db.settings.put(defaults);
  }
}
